import "@/styles/globals.css";

import type { Metadata } from "next";
import { Inter, JetBrains_Mono } from "next/font/google";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import { Toaster } from "sonner";
import { ThemeProvider } from "@/components/theme-provider";
import { cn } from "@/lib/utils";
import { TRPCReactProvider } from "@/trpc/react";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
});

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
  authModal,
}: Readonly<{ children: React.ReactNode; authModal: React.ReactNode }>) {
  return (
    <html
      className={cn(
        "bg-background font-mono",
        jetbrainsMono.variable,
        "font-sans",
        inter.variable,
      )}
      lang="en"
      suppressHydrationWarning
    >
      <body>
        <NuqsAdapter>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            disableTransitionOnChange
            enableSystem
          >
            <TRPCReactProvider>
              <Toaster richColors />
              {children}
              {authModal}
              <footer className="flex h-14 items-center justify-center text-muted-foreground">
                Built by Shreesha & Team
              </footer>
            </TRPCReactProvider>
          </ThemeProvider>
        </NuqsAdapter>
      </body>
    </html>
  );
}
